# Generated by Django 5.0.7 on 2024-07-12 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomodel',
            name='preview',
            field=models.FileField(default=django.utils.timezone.now, upload_to='thumbnails/'),
        ),
    ]
